### PR TITLE
Applied JSON relative URL about:blank workaround. Fixes issue #27

### PR DESCRIPTION
**Pull request by volkert-fastned**
See https://github.com/swagger-api/swagger-ui/issues/4107 for the underlying upstream Swagger UI issue.

### CODE REVIEW

**Comment by volkert-fastned** [comment]
@JLLeitschuh I updated the affected tests and also tested this manually by running the submodule `ktor-sample-swagger` locally. That worked.

**Comment by JLLeitschuh** [comment]
LGTM!

**Comment by volkert-fastned** [comment]
@JLLeitschuh Cool! Could you please publish a release of this to Maven Central or JCenter? A minor version bump should suffice. Thanks. 😃

**Comment by JLLeitschuh** [comment]
Version 0.5.0 is now published.

**Pull request merged**
