### PR TITLE
Added operationId function to Metadata to explicitly set operationId

### PR DESCRIPTION
**Pull request by frnknglrt**
Added operationId parameter to OpenAPI Metadata Object and implemented test case to ensure proper usage in generated openApi description file.

Reason for change:
Many code generators primarily use the operationId for generating client side method names. Setting this field allows to control how the generated code on the client side looks like. Also it becomes possible to change the default method names. This is quite handy if the default names are not meaningful enough or must be overridden for legacy reasons.

Limitations:
According to the documentation, the operationId must be unique within a api. The code does not contain any checks to ensure uniqueness. The developer must carefully assign operationIds to avoid naming conflicts

Example:
added operationId "getAllShapes" to GET /shapes operation. When a client is generated, the method to call this operation is getAllShapes().

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Let me know when this is ready to be merged, so far, this change seems fine.

**Comment by frnknglrt** [comment]
Hello, 

sorry for the issues. I was not aware of the style guideline beforehands. Sorry for that. It's fixed now and if its fine for you, it can be merged

Thanks for your reply and all the best,

Frank

**Comment by JLLeitschuh** [comment]
Would you be willing to try out using JitPack to build this release for you?

I don't really have the cycles to get a release out to people right now unfortunately.

If it doesn't work, I'll see what I can do later this week.

**Comment by frnknglrt** [comment]
Hello,

i'm now using jitpack to get the latest release. Works fine for me. It's also nice that I can use your security extension now. 

Thanks and best,

Frank

**Pull request merged**
