### PR TITLE
Add support for patch

### PR DESCRIPTION
**Pull request by nilsmagnus**
This solves #34

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Can you do me the quick favor of adding a test to this, please?
It looks right, but this is sanity checking for future changes.

Thanks!

**Comment by nilsmagnus** [comment]
@JLLeitschuh tests are now in place.

**Comment by nilsmagnus** [comment]
Thanks for reviewing and accepting the PR. Is it going to be in a minor-release any time soon?

**Comment by JLLeitschuh** [comment]
@nilsmagnus Are you willing to give JitPack.io a shot to see if you can get a release that way?

https://jitpack.io/

If it works, it will significantly reduce the maintenance requirements for me to publish releases.

**Pull request merged**
